# Generated by Django 3.0.7 on 2020-06-13 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journaltitle', models.CharField(max_length=200)),
                ('url', models.URLField(default='?')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
